"""Cloud database model — cloud_cases table (JSONB) as per spec."""
from datetime import datetime
from sqlalchemy import Column, DateTime, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import declarative_base
import uuid

Base = declarative_base()


def _uid():
    return str(uuid.uuid4())


class CloudCase(Base):
    """
    Stores the case summary sent from edge + the executive plan generated by 27B model.
    Raw vitals are NEVER sent to cloud (privacy-aware architecture).
    """
    __tablename__ = "cloud_cases"

    id = Column(UUID(as_uuid=False), primary_key=True, default=_uid)
    case_summary = Column(JSONB, nullable=False)    # structured risk + guideline summary
    executive_plan = Column(Text, nullable=True)    # full text plan from 27B
    created_at = Column(DateTime, default=datetime.utcnow)
